### ISSUE TITLE
Create infrastructure to run the C++ program with any of the BBOB functions

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#1]
The functions are [in this repo](https://github.com/numbbo/coco/tree/master/code-experiments/src). We will probably need to copy them here so that we can refactor them if needed.

We will use the first 2 functions from every [BBOB category](http://numbbo.github.io/coco/testsuites/bbob)

**Comment by gstvrmrlpz** [comment]
mini eo here?

**Comment by JJ** [comment]
For the time being, just the functions.

**Comment by gstvrmrlpz** [comment]
done
