### ISSUE TITLE
Running the compiled program with c++-2a crashes

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#12]
I try to run it with:

```
./fp -f sphere -t double
*** stack smashing detected ***: terminated
[1]    93890 abort (core dumped)  ./fp -f sphere -t double
```

Same with other combinations. This is also compiled with g++-10, but I don't think that should be an issue. Please checi that size=0z has been changed to size=0, I don't know if that's an issue.

**Comment by gstvrmrlpz** [comment]
No clue, but we can remove C++23... done
