### ISSUE TITLE
Separate generation of chromosomes (for baseline measurements) from function measurement

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#13]
Same as it's done before, try to separate them and use generation as baseline

**Comment by gstvrmrlpz** [comment]
I can do that but why?
Floating point numbers are used in two places:
1) random number generation of individuals
2) fitness evaluation
We are supposed to measure the different of both changing the floating point size... don't we?

**Comment by gstvrmrlpz** [comment]
done with init only option
