### ISSUE TITLE
We need to run it for different sizes

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#14]
Check the usual BBOB sizes, which go up to 100

**Comment by gstvrmrlpz** [comment]
Now we are using 100... should I add another option to the parser?

**Comment by JJ** [comment]
> Now we are using 100... should I add another option to the parser?

Well, the sizes that are actually used in BBOB would help. [These are the sizes](http://numbbo.github.io/coco/testsuites/bbob). 20, 40 and 100 would be enough, I guess (and 100 is not even in BBOB)

**Comment by gstvrmrlpz** [comment]
done!
