### ISSUE TITLE
Set up measurements for GPU

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#15]
Try to measure not PKG, but GPU which is a different thing.

**Comment by gstvrmrlpz** [comment]
we are not using the GPU....

**Comment by JJ** [comment]
You might be right that PKG is also including all floating-point operations and registers, but I'd rather check. In principle, perf and pinpoint do measure GPU independently of PKG.

**Comment by JJ** [comment]
Well, not really; if energy consumption is not too high moving it to GPU might not be worth the while.
