### ISSUE TITLE
Decide on title

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#22]
Think about a title that summarizes the work that has been done

Some suggestions

1. Energy consumption of BBOB functions in the low-level language C++
2. Explaining and optimizing energy consumption of BBOB functions in the
   low-level language C++
3. Any other?

**Comment by gstvrmrlpz** [comment]
cost of standard floating point types?
we can add 1... it make sense
2 is too low level and difficult, not worth I think
There is still a light evolutionary thing in our code... we may add it also
