### ISSUE TITLE
Create generation of floating point vectors

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#3]
Using for the time being just two data structures: simple and double precision

**Comment by gstvrmrlpz** [comment]
long double is almost done for free with the actual implementation...
do I have to remove it?

**Comment by gstvrmrlpz** [comment]
float and double are done with CPU in MMX registers
long double are done with CPU and old FPU registers
I don't know why

**Comment by JJ** [comment]
> long double is almost done for free with the actual implementation... do I have to remove it?

No, that's a result too.

**Comment by JJ** [comment]
> float and double are done with CPU in MMX registers long double are done with CPU and old FPU registers I don't know why

So we have here
* fmul That's part of what exactly? MMX?
* intrinsics That's part of AVX, correct? Is that used?
* Any other I'm missing?

**Comment by gstvrmrlpz** [comment]
done!
