### ISSUE TITLE
Try with simple changes: double to single precision

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#5]
Check what kind of improvements it makes.

**Comment by gstvrmrlpz** [comment]
very small as can be seen in the initial experiments

**Comment by JJ** [comment]
But we have not measured GPU yet...

**Comment by gstvrmrlpz** [comment]
future work!

**Comment by JJ** [comment]
We're using float/double and comparing it. It's already programmed, so we can close, but it's not future but present work.
