### ISSUE TITLE
Check using single-machine-instruction functions

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#6]
Such as FMA (`fma` in C++, or `fmaf` for single precision

**Comment by gstvrmrlpz** [comment]
it is so much complex... see rastrigin for floats as an example:

`00000000004027e0 <float rastrigin_function<std::array<float, 100ul>, float>(std::array<float, 100ul> const&)>:
  4027e0:	41 55                	push   %r13
  4027e2:	41 54                	push   %r12
  4027e4:	55                   	push   %rbp
  4027e5:	49 89 fd             	mov    %rdi,%r13
  4027e8:	53                   	push   %rbx
  4027e9:	4c 8d a7 90 01 00 00 	lea    0x190(%rdi),%r12
  4027f0:	31 ed                	xor    %ebp,%ebp
  4027f2:	31 db                	xor    %ebx,%ebx
  4027f4:	48 83 ec 18          	sub    $0x18,%rsp
  4027f8:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
  4027ff:	00 
  402800:	c4 c1 7a 10 4d 00    	vmovss 0x0(%r13),%xmm1
  402806:	49 83 c5 04          	add    $0x4,%r13
  40280a:	c5 f2 5a c1          	vcvtss2sd %xmm1,%xmm1,%xmm0
  40280e:	c5 fb 59 05 ea 27 00 	vmulsd 0x27ea(%rip),%xmm0,%xmm0        # 405000 <__dso_handle+0x320>
  402815:	00 
  402816:	c5 fa 11 4c 24 0c    	vmovss %xmm1,0xc(%rsp)
  40281c:	e8 df e9 ff ff       	call   401200 <cos@plt>
  402821:	c5 fa 10 4c 24 0c    	vmovss 0xc(%rsp),%xmm1
  402827:	c5 f9 6e db          	vmovd  %ebx,%xmm3
  40282b:	c5 f9 6e f5          	vmovd  %ebp,%xmm6
  40282f:	c5 f9 28 d0          	vmovapd %xmm0,%xmm2
  402833:	c5 e2 5a c3          	vcvtss2sd %xmm3,%xmm3,%xmm0
  402837:	c5 fb 58 c2          	vaddsd %xmm2,%xmm0,%xmm0
  40283b:	c5 fb 5a e0          	vcvtsd2ss %xmm0,%xmm0,%xmm4
  40283f:	c5 f2 59 c9          	vmulss %xmm1,%xmm1,%xmm1
  402843:	c5 f9 7e e3          	vmovd  %xmm4,%ebx
  402847:	c5 ca 58 e9          	vaddss %xmm1,%xmm6,%xmm5
  40284b:	c5 f9 7e ed          	vmovd  %xmm5,%ebp
  40284f:	4d 39 ec             	cmp    %r13,%r12
  402852:	75 ac                	jne    402800 <float rastrigin_function<std::array<float, 100ul>, float>(std::array<float, 100ul> const&)+0x20>
  402854:	c5 fa 10 05 4c 24 00 	vmovss 0x244c(%rip),%xmm0        # 404ca8 <_IO_stdin_used+0x8>
  40285b:	00 
  40285c:	c5 d2 5a cd          	vcvtss2sd %xmm5,%xmm5,%xmm1
  402860:	c5 fa 5c c4          	vsubss %xmm4,%xmm0,%xmm0
  402864:	c5 fa 5a c0          	vcvtss2sd %xmm0,%xmm0,%xmm0
  402868:	c4 e2 f1 99 05 87 27 	vfmadd132sd 0x2787(%rip),%xmm1,%xmm0        # 404ff8 <__dso_handle+0x318>
  40286f:	00 00 
  402871:	48 83 c4 18          	add    $0x18,%rsp
  402875:	5b                   	pop    %rbx
  402876:	5d                   	pop    %rbp
  402877:	41 5c                	pop    %r12
  402879:	41 5d                	pop    %r13
  40287b:	c5 fb 5a c0          	vcvtsd2ss %xmm0,%xmm0,%xmm0
  40287f:	c3                   	ret

**Comment by JJ** [comment]
OK, give me some hints here. XMM look like MMX registers? So that's the only optimization that's being done?

**Comment by gstvrmrlpz** [comment]
done!

**Comment by JJ** [comment]
This is actually superseded by #20. We're simply using those instructions issued by the compiler.
