### ISSUE TITLE
Check energy savings with radical AVX/SSE2 precision

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#7]
Which will probably need a big refactoring. Two versions also

- Double precision quad operations (not sure this works in my AMD)
- Single precision quad operations

**Comment by gstvrmrlpz** [comment]
the compiler is using multimedia instructions... 
Do you want to avoid them?

**Comment by JJ** [comment]
No, why would I? Can you show me where? It's using MMX, not AVX though, right?

**Comment by gstvrmrlpz** [comment]
using best instructions for every cpu

**Comment by JJ** [comment]
Again, superseded by #20. We still need to check. SSE2 instructions (multiply/add) seem to be issued by the compiler too.
