### ISSUE TITLE
fp issues a segmentation fault by itself

### ISSUE THREAD

**Issue by JJ** [JJ/energy-bbob#9]
I'm using g++-14 on the Mac with Apple Silicon.

I'm not totally sure it's the only reason. Might be related to #12

**Comment by gstvrmrlpz** [comment]
try now and tell me...

**Comment by JJ** [comment]
Fails in exactly the same way. If you make a reference to this issue like this `#9` in the commit message I will be able to see exactly what you have done.

**Comment by gstvrmrlpz** [comment]
fixed!
